//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.bidib.netbidibc.core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("org.bidib.netbidibc.core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA.
        /// </summary>
        public static string AccessoryDirection {
            get {
                return ResourceManager.GetString("AccessoryDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;.
        /// </summary>
        public static string BackwardDirection {
            get {
                return ResourceManager.GetString("BackwardDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string BIDIB_BST_STATE_OFF {
            get {
                return ResourceManager.GetString("BIDIB_BST_STATE_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off (on requested).
        /// </summary>
        public static string BIDIB_BST_STATE_OFF_GO_REQ {
            get {
                return ResourceManager.GetString("BIDIB_BST_STATE_OFF_GO_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off (by local key).
        /// </summary>
        public static string BIDIB_BST_STATE_OFF_HERE {
            get {
                return ResourceManager.GetString("BIDIB_BST_STATE_OFF_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off (high temperature).
        /// </summary>
        public static string BIDIB_BST_STATE_OFF_HOT {
            get {
                return ResourceManager.GetString("BIDIB_BST_STATE_OFF_HOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off (no DCC).
        /// </summary>
        public static string BIDIB_BST_STATE_OFF_NO_DCC {
            get {
                return ResourceManager.GetString("BIDIB_BST_STATE_OFF_NO_DCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off (no power).
        /// </summary>
        public static string BIDIB_BST_STATE_OFF_NOPOWER {
            get {
                return ResourceManager.GetString("BIDIB_BST_STATE_OFF_NOPOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off (short).
        /// </summary>
        public static string BIDIB_BST_STATE_OFF_SHORT {
            get {
                return ResourceManager.GetString("BIDIB_BST_STATE_OFF_SHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string BIDIB_BST_STATE_ON {
            get {
                return ResourceManager.GetString("BIDIB_BST_STATE_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On (by local key).
        /// </summary>
        public static string BIDIB_BST_STATE_ON_HERE {
            get {
                return ResourceManager.GetString("BIDIB_BST_STATE_ON_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On (high temperature).
        /// </summary>
        public static string BIDIB_BST_STATE_ON_HOT {
            get {
                return ResourceManager.GetString("BIDIB_BST_STATE_ON_HOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On (current limit).
        /// </summary>
        public static string BIDIB_BST_STATE_ON_LIMIT {
            get {
                return ResourceManager.GetString("BIDIB_BST_STATE_ON_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On (off requested).
        /// </summary>
        public static string BIDIB_BST_STATE_ON_STOP_REQ {
            get {
                return ResourceManager.GetString("BIDIB_BST_STATE_ON_STOP_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        public static string BIDIB_CS_STATE_BUSY {
            get {
                return ResourceManager.GetString("BIDIB_CS_STATE_BUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On (with watchdog).
        /// </summary>
        public static string BIDIB_CS_STATE_GO {
            get {
                return ResourceManager.GetString("BIDIB_CS_STATE_GO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On (permanent).
        /// </summary>
        public static string BIDIB_CS_STATE_GO_IGN_WD {
            get {
                return ResourceManager.GetString("BIDIB_CS_STATE_GO_IGN_WD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string BIDIB_CS_STATE_OFF {
            get {
                return ResourceManager.GetString("BIDIB_CS_STATE_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming.
        /// </summary>
        public static string BIDIB_CS_STATE_PROG {
            get {
                return ResourceManager.GetString("BIDIB_CS_STATE_PROG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy programming.
        /// </summary>
        public static string BIDIB_CS_STATE_PROGBUSY {
            get {
                return ResourceManager.GetString("BIDIB_CS_STATE_PROGBUSY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Softstop.
        /// </summary>
        public static string BIDIB_CS_STATE_SOFTSTOP {
            get {
                return ResourceManager.GetString("BIDIB_CS_STATE_SOFTSTOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string BIDIB_CS_STATE_STOP {
            get {
                return ResourceManager.GetString("BIDIB_CS_STATE_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        public static string Centimeter {
            get {
                return ResourceManager.GetString("Centimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection has been closed by remote side!.
        /// </summary>
        public static string ConnectionClosedByRemote {
            get {
                return ResourceManager.GetString("ConnectionClosedByRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout! Connection could not be established..
        /// </summary>
        public static string ConnectionProcessTimedOut {
            get {
                return ResourceManager.GetString("ConnectionProcessTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        public static string DegreeCelcius {
            get {
                return ResourceManager.GetString("DegreeCelcius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency stop.
        /// </summary>
        public static string EmergencyStop {
            get {
                return ResourceManager.GetString("EmergencyStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to interface! 
        ///Please check your connection settings..
        /// </summary>
        public static string Error_CouldNotConnectToInterface {
            get {
                return ResourceManager.GetString("Error_CouldNotConnectToInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to serial COM port &apos;{0}&apos;!
        ///Please check the interface settings and the connection. 
        ///- is COM port correct?
        ///- is the USB cabel connected?
        ///- is the port already used by another application?.
        /// </summary>
        public static string Error_CouldNotConnectToSerialInterface {
            get {
                return ResourceManager.GetString("Error_CouldNotConnectToSerialInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not establish interface connection on IP &apos;{0}&apos;.
        /// </summary>
        public static string Error_CouldNotConnectToSocket {
            get {
                return ResourceManager.GetString("Error_CouldNotConnectToSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface did not respond on any request. Please check your configuration!.
        /// </summary>
        public static string Error_NoResponseFromInterface {
            get {
                return ResourceManager.GetString("Error_NoResponseFromInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data result is not a socket!.
        /// </summary>
        public static string Error_NoSocket {
            get {
                return ResourceManager.GetString("Error_NoSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection service is not configured for any connection..
        /// </summary>
        public static string Error_NotConfiguredForConnection {
            get {
                return ResourceManager.GetString("Error_NotConfiguredForConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot send message - Serial Port NOT connected or open.
        /// </summary>
        public static string Error_SerialPortNotConnected {
            get {
                return ResourceManager.GetString("Error_SerialPortNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when handling received data.
        /// </summary>
        public static string Error_SocketData {
            get {
                return ResourceManager.GetString("Error_SocketData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket has been disposed!.
        /// </summary>
        public static string Error_SocketDisposed {
            get {
                return ResourceManager.GetString("Error_SocketDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assesory (Ext.).
        /// </summary>
        public static string ExtendedAccessory {
            get {
                return ResourceManager.GetString("ExtendedAccessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EA.
        /// </summary>
        public static string ExtendedAccessoryDirection {
            get {
                return ResourceManager.GetString("ExtendedAccessoryDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; is not defined for current schema {1}..
        /// </summary>
        public static string FileHasNoDefinedSchema {
            get {
                return ResourceManager.GetString("FileHasNoDefinedSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml file &apos;{0}&apos; is not valid based on schema {1}..
        /// </summary>
        public static string FileNotValidWithSchema {
            get {
                return ResourceManager.GetString("FileNotValidWithSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;.
        /// </summary>
        public static string ForwardDirection {
            get {
                return ResourceManager.GetString("ForwardDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        public static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hz.
        /// </summary>
        public static string Hertz {
            get {
                return ResourceManager.GetString("Hertz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifying ....
        /// </summary>
        public static string Identifying {
            get {
                return ResourceManager.GetString("Identifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in operation.
        /// </summary>
        public static string Idle {
            get {
                return ResourceManager.GetString("Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input message queue processing canceled.
        /// </summary>
        public static string InputQueueProcessingCanceled {
            get {
                return ResourceManager.GetString("InputQueueProcessingCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input message queue processing finished.
        /// </summary>
        public static string InputQueueProcessingFinished {
            get {
                return ResourceManager.GetString("InputQueueProcessingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface is not connected! Message will not be transmitted!.
        /// </summary>
        public static string InterfaceNotConnectedNoTransmission {
            get {
                return ResourceManager.GetString("InterfaceNotConnectedNoTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km/h.
        /// </summary>
        public static string KilometerPerHour {
            get {
                return ResourceManager.GetString("KilometerPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kw.
        /// </summary>
        public static string Kilowatts {
            get {
                return ResourceManager.GetString("Kilowatts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locomotiv.
        /// </summary>
        public static string Loco {
            get {
                return ResourceManager.GetString("Loco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loco w. sound.
        /// </summary>
        public static string LocoSound {
            get {
                return ResourceManager.GetString("LocoSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mA.
        /// </summary>
        public static string MilliAmpere {
            get {
                return ResourceManager.GetString("MilliAmpere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string Millimeter {
            get {
                return ResourceManager.GetString("Millimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm/s.
        /// </summary>
        public static string MillimeterPerSecond {
            get {
                return ResourceManager.GetString("MillimeterPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mΩ.
        /// </summary>
        public static string MilliOhm {
            get {
                return ResourceManager.GetString("MilliOhm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string MilliSecond {
            get {
                return ResourceManager.GetString("MilliSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to netBiDiB.
        /// </summary>
        public static string NetBiDiB {
            get {
                return ResourceManager.GetString("NetBiDiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation (network).
        /// </summary>
        public static string NetworkSimulation {
            get {
                return ResourceManager.GetString("NetworkSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP Interface.
        /// </summary>
        public static string NetworkTcp {
            get {
                return ResourceManager.GetString("NetworkTcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node is available for control.
        /// </summary>
        public static string NodeAvailableForControl {
            get {
                return ResourceManager.GetString("NodeAvailableForControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node is currently controlled by &apos;{0}&apos;.
        /// </summary>
        public static string NodeControlledByOther {
            get {
                return ResourceManager.GetString("NodeControlledByOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NoUnit {
            get {
                return ResourceManager.GetString("NoUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ω.
        /// </summary>
        public static string Ohm {
            get {
                return ResourceManager.GetString("Ohm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output message queue processing canceled.
        /// </summary>
        public static string OutputQueueProcessingCanceled {
            get {
                return ResourceManager.GetString("OutputQueueProcessingCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output message queue processing finished.
        /// </summary>
        public static string OutputQueueProcessingFinished {
            get {
                return ResourceManager.GetString("OutputQueueProcessingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pairing process was aborted!.
        /// </summary>
        public static string PairingProcessAborted {
            get {
                return ResourceManager.GetString("PairingProcessAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote client rejected the pairing request.
        /// </summary>
        public static string PairingRejectedByRemote {
            get {
                return ResourceManager.GetString("PairingRejectedByRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        public static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rad/s.
        /// </summary>
        public static string RadPerSecond {
            get {
                return ResourceManager.GetString("RadPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read only.
        /// </summary>
        public static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read / write.
        /// </summary>
        public static string ReadWrite {
            get {
                return ResourceManager.GetString("ReadWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rpm.
        /// </summary>
        public static string RevolutionsPerMinute {
            get {
                return ResourceManager.GetString("RevolutionsPerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rpm/V.
        /// </summary>
        public static string RevolutionsPerMinutePerVolt {
            get {
                return ResourceManager.GetString("RevolutionsPerMinutePerVolt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in motion.
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The xml schema must not be null..
        /// </summary>
        public static string SchemaMustNotBeNull {
            get {
                return ResourceManager.GetString("SchemaMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial-over-TCP.
        /// </summary>
        public static string SerialOverTcp {
            get {
                return ResourceManager.GetString("SerialOverTcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Interface.
        /// </summary>
        public static string SerialPort {
            get {
                return ResourceManager.GetString("SerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open serial port &apos;{0}&apos;! {1}.
        /// </summary>
        public static string SerialPortConnectionError {
            get {
                return ResourceManager.GetString("SerialPortConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation (serial).
        /// </summary>
        public static string SerialSimulation {
            get {
                return ResourceManager.GetString("SerialSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation.
        /// </summary>
        public static string Simulation {
            get {
                return ResourceManager.GetString("Simulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessory.
        /// </summary>
        public static string StandardAccessory {
            get {
                return ResourceManager.GetString("StandardAccessory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Susi.
        /// </summary>
        public static string Susi {
            get {
                return ResourceManager.GetString("Susi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Susi w. sound.
        /// </summary>
        public static string SusiSound {
            get {
                return ResourceManager.GetString("SusiSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t.
        /// </summary>
        public static string Tonnes {
            get {
                return ResourceManager.GetString("Tonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V.
        /// </summary>
        public static string Volts {
            get {
                return ResourceManager.GetString("Volts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to write only.
        /// </summary>
        public static string WriteOnly {
            get {
                return ResourceManager.GetString("WriteOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not execute xml validation. The file &apos;{0}&apos; does not exist or is empty..
        /// </summary>
        public static string XmlValidationFileError {
            get {
                return ResourceManager.GetString("XmlValidationFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not validate file {0} with schema {1} {2}..
        /// </summary>
        public static string XmlValidationProcessError {
            get {
                return ResourceManager.GetString("XmlValidationProcessError", resourceCulture);
            }
        }
    }
}
